# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    - name: Run Tests
      run: mvn test --file pom.xml
  
  run_static_code_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: PMD Source Code Analyzer 
      run: mvn pmd:check --file pom.xml
  
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Release Project
      run: mvn package -DskipTests --file pom.xml
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_release]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy Project
      run: mvn package -DskipTests --file pom.xml
